### ISSUE TITLE
"TextEncoder is not a constructor" Error when using EthrDID library

### ISSUE THREAD

**Issue by andrazvrecko** [MetaMask/snaps-skunkworks#247]
I'm trying to use [EthrDID ](https://github.com/uport-project/ethr-did) library inside the Snap, but I get the following error, while using `mm-snap eval`:
```
TypeError: TextEncoder is not a constructor
  at Object.201 (eval at <anonymous> (eval at makeEvaluateFactory (C:\Users\pokem\AppData\Local\Yarn\Data\global\node_modules\ses\dist\ses.cjs:1401:10)), <anonymous>:66418:21)
  at o (eval at <anonymous> (eval at makeEvaluateFactory (C:\Users\pokem\AppData\Local\Yarn\Data\global\node_modules\ses\dist\ses.cjs:1401:10)), <anonymous>:2:265)
  at eval (eval at <anonymous> (eval at makeEvaluateFactory (C:\Users\pokem\AppData\Local\Yarn\Data\global\node_modules\ses\dist\ses.cjs:1401:10)), <anonymous>:2:316)
  at Object.198../bases/base10.js (eval at <anonymous> (eval at makeEvaluateFactory (C:\Users\pokem\AppData\Local\Yarn\Data\global\node_modules\ses\dist\ses.cjs:1401:10)), <anonymous>:65922:12)
  at o (eval at <anonymous> (eval at makeEvaluateFactory (C:\Users\pokem\AppData\Local\Yarn\Data\global\node_modules\ses\dist\ses.cjs:1401:10)), <anonymous>:2:265)
  at eval (eval at <anonymous> (eval at makeEvaluateFactory (C:\Users\pokem\AppData\Local\Yarn\Data\global\node_modules\ses\dist\ses.cjs:1401:10)), <anonymous>:2:316)
  at Object.218.@babel/runtime/helpers/defineProperty (eval at <anonymous> (eval at makeEvaluateFactory (C:\Users\pokem\AppData\Local\Yarn\Data\global\node_modules\ses\dist\ses.cjs:1401:10)), <anonymous>:67592:14)
  at o (eval at <anonymous> (eval at makeEvaluateFactory (C:\Users\pokem\AppData\Local\Yarn\Data\global\node_modules\ses\dist\ses.cjs:1401:10)), <anonymous>:2:265)
  at eval (eval at <anonymous> (eval at makeEvaluateFactory (C:\Users\pokem\AppData\Local\Yarn\Data\global\node_modules\ses\dist\ses.cjs:1401:10)), <anonymous>:2:316)
  at Object.215../util/bases.js (eval at <anonymous> (eval at makeEvaluateFactory (C:\Users\pokem\AppData\Local\Yarn\Data\global\node_modules\ses\dist\ses.cjs:1401:10)), <anonymous>:67520:13)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
```
This is one of 3 sections from the bundle.js file, where the constructor is called:

```
},{"./bases/base32.js":192,"./bases/base58.js":194,"./bytes.js":199,"./hashes/digest.js":203,"./varint.js":208}],201:[function(require,module,exports){
'use strict';

Object.defineProperty(exports, '__esModule', {
  value: true
});


const name = 'json';
const code = 512;

const encode = node => new TextEncoder().encode(JSON.stringify(node));

const decode = data => JSON.parse(new TextDecoder().decode(data));

exports.code = code;
exports.decode = decode;
exports.encode = encode;
exports.name = name;
```

I suspect TextEncoder is used when trying to sing a JWT:

```
 const keypair = EthrDID.createKeyPair();
 const ethrDid = new EthrDID({...keypair});
 const helloJWT = await ethrDid.signJWT({hello: 'world'})
```

If I'm not mistaken, TextEncoder is a class from the node.js util library, which Browserify should provide. I tried fixing this by using `require('util');`, however they do not provide TextEncoder and TextDecoder classes. 

Help would be greatly appreciated, Thanks!

**Comment by andrazvrecko** [comment]
I managed to get through `mm-snap eval`, by adding following code to `post-process.js`:
```
bundleString = bundleString.replace('const textEncoder = new TextEncoder();', "")
bundleString = bundleString.replace('const textDecoder = new TextDecoder();', "")
bundleString = bundleString.replace('textEncoder.', 'new TextEncoder().')
bundleString = bundleString.replace('textDecoder.', 'new TextDecoder().')
```

Now my snap installs, however, it throws a "Problem happened: TextEncoder is not a constructor" error when I try to run the function. Web App and MetaMask consoles throw similar "RPC ... TextEncoder is not a constructor" errors. Furthermore, if I copy and paste problematic code from bundle.js directly into MetaMask extension console, everything works perfectly.

**Comment by FrederikBolding** [comment]
@andrazvrecko These APIs are currently not automatically exposed to Snaps, but we will be making changes to expose a few more APIs by default to Snaps.

**Comment by andrazvrecko** [comment]
I saw TextEncoder/Decoder APIs have been exposed to snaps in the recent 0.10.0 version of the lib. I installed latest version and tried running mm-snap build, however I still get the `TypeError: TextEncoder is not a constructor`. I am using node v17.4.0.

Is there something I'm missing? Do I have to change snap.config in order to make it work?

**Comment by FrederikBolding** [comment]
We're still integrating this new version into the MetaMask extension, so hold on for a bit longer 😄

To improve the error message situation we also need #258

**Comment by FrederikBolding** [comment]
@andrazvrecko If you are comfortable building and running MetaMask Flask yourself, you can run this branch and test your Snap: https://github.com/MetaMask/metamask-extension/tree/eth-denver-2022

You can still run your Snap as it does produce a `bundle.js` even if you get the `TextEncoder` error.
