### ISSUE TITLE
Cannot find module `@metamask\execution-environments\dist\index.js`

### ISSUE THREAD

**Issue by anudit** [MetaMask/snaps-skunkworks#302]
While using the the latest release `0.10.3` to try out `snap_notify` I run into the following error.

```js
$ mm-snap build
internal/modules/cjs/loader.js:329
      throw err;
      ^

Error: Cannot find module 'D:\Users\anudit\Documents\Github\omnidsnap\node_modules\@metamask\execution-environments\dist\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:534:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (D:\Users\anudit\Documents\Github\omnidsnap\node_modules\@metamask\snap-controllers\dist\services\WebWorkerExecutionService.js:9:34)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'D:\\Users\\anudit\\Documents\\Github\\omnidsnap\\node_modules\\@metamask\\execution-environments\\package.json',
  requestPath: '@metamask/execution-environments'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 

```
GitHub Actions run https://github.com/anudit/omnidsnap/runs/5625698027?check_suite_focus=true#step:8:10
Snap Codebase for reproduction: https://github.com/anudit/omnidsnap

cc : @rekmarks

**Comment by FrederikBolding** [comment]
Thanks for reporting! Looking into this 👍

**Comment by FrederikBolding** [comment]
Fixed in #303
