### ISSUE TITLE
Tests fail when run from root on Mac

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps-skunkworks#536]
When tests are run in the main workspace root on Mac the tests fail.
This problem doesn't appear when tests are run inside the packages itself instead of root.

```
> node --version
v18.3.0
> yarn --version
3.2.1
> sw_vers -productVersion
12.4
> uname -m
x86_64
```

WebPack plugin failing:
```
➤ YN0000: [@metamask/snaps-webpack-plugin]: Process started
➤ YN0000: [@metamask/snaps-webpack-plugin]: -----------|---------|----------|---------|---------|-------------------
➤ YN0000: [@metamask/snaps-webpack-plugin]: File       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
➤ YN0000: [@metamask/snaps-webpack-plugin]: -----------|---------|----------|---------|---------|-------------------
➤ YN0000: [@metamask/snaps-webpack-plugin]: All files  |     100 |      100 |     100 |     100 |
➤ YN0000: [@metamask/snaps-webpack-plugin]:  plugin.ts |     100 |      100 |     100 |     100 |
➤ YN0000: [@metamask/snaps-webpack-plugin]: -----------|---------|----------|---------|---------|-------------------
➤ YN0000: [@metamask/snaps-webpack-plugin]: FAIL src/plugin.test.ts (12.887 s)
➤ YN0000: [@metamask/snaps-webpack-plugin]:   SnapsWebpackPlugin
➤ YN0000: [@metamask/snaps-webpack-plugin]:     ✕ processes files using Webpack (3281 ms)
➤ YN0000: [@metamask/snaps-webpack-plugin]:     ✓ applies a transform (1414 ms)
➤ YN0000: [@metamask/snaps-webpack-plugin]:     ✓ forwards the options (553 ms)
➤ YN0000: [@metamask/snaps-webpack-plugin]:     ✓ runs on the entire bundle (219 ms)
➤ YN0000: [@metamask/snaps-webpack-plugin]:
➤ YN0000: [@metamask/snaps-webpack-plugin]:   ● SnapsWebpackPlugin › processes files using Webpack
➤ YN0000: [@metamask/snaps-webpack-plugin]:
➤ YN0000: [@metamask/snaps-webpack-plugin]:     thrown: "Exceeded timeout of 2500 ms for a test.
➤ YN0000: [@metamask/snaps-webpack-plugin]:     Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
➤ YN0000: [@metamask/snaps-webpack-plugin]:
➤ YN0000: [@metamask/snaps-webpack-plugin]:        7 |
➤ YN0000: [@metamask/snaps-webpack-plugin]:        8 | describe('SnapsWebpackPlugin', () => {
➤ YN0000: [@metamask/snaps-webpack-plugin]:     >  9 |   it('processes files using Webpack', async () => {
➤ YN0000: [@metamask/snaps-webpack-plugin]:          |   ^
➤ YN0000: [@metamask/snaps-webpack-plugin]:       10 |     const fileSystem = createFsFromVolume(new Volume());
➤ YN0000: [@metamask/snaps-webpack-plugin]:       11 |     const { promises: fs } = fileSystem;
➤ YN0000: [@metamask/snaps-webpack-plugin]:       12 |
➤ YN0000: [@metamask/snaps-webpack-plugin]:
➤ YN0000: [@metamask/snaps-webpack-plugin]:       at src/plugin.test.ts:9:3
➤ YN0000: [@metamask/snaps-webpack-plugin]:       at Object.<anonymous> (src/plugin.test.ts:8:1)
➤ YN0000: [@metamask/snaps-webpack-plugin]:
➤ YN0000: [@metamask/snaps-webpack-plugin]:  › 4 snapshots written.
➤ YN0000: [@metamask/snaps-webpack-plugin]: Snapshot Summary
➤ YN0000: [@metamask/snaps-webpack-plugin]:  › 4 snapshots written from 1 test suite.
➤ YN0000: [@metamask/snaps-webpack-plugin]:
➤ YN0000: [@metamask/snaps-webpack-plugin]: Test Suites: 1 failed, 1 total
➤ YN0000: [@metamask/snaps-webpack-plugin]: Tests:       1 failed, 3 passed, 4 total
➤ YN0000: [@metamask/snaps-webpack-plugin]: Snapshots:   4 written, 4 total
➤ YN0000: [@metamask/snaps-webpack-plugin]: Time:        15.756 s, estimated 16 s
➤ YN0000: [@metamask/snaps-webpack-plugin]: Ran all test suites.
➤ YN0000: [@metamask/snaps-webpack-plugin]: Process exited (exit code 1), completed in 19s 926ms
```

Controllers failing:
```
➤ YN0000: [@metamask/snap-controllers]: PASS runner: electron src/snaps/RequestQueue.test.ts
➤ YN0000: [@metamask/snap-controllers]: PASS runner: electron src/snaps/utils.test.ts
➤ YN0000: [@metamask/snap-controllers]: PASS runner: electron src/snaps/endowments/long-running.test.ts
➤ YN0000: [@metamask/snap-controllers]: PASS runner: electron src/snaps/endowments/network-access.test.ts
➤ YN0000: [@metamask/snap-controllers]: PASS runner: electron src/services/WebWorkerExecutionService.test.ts
➤ YN0000: [@metamask/snap-controllers]: FAIL runner: electron src/services/iframe/IframeExecutionService.test.ts
➤ YN0000: [@metamask/snap-controllers]:   ● IframeExecutionService › can create a snap worker and start the snap
➤ YN0000: [@metamask/snap-controllers]:
➤ YN0000: [@metamask/snap-controllers]:     : Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 5000 ms timeout specified by jest.setTimeout.Error:
➤ YN0000: [@metamask/snap-controllers]:
➤ YN0000: [@metamask/snap-controllers]:       47 |   });
➤ YN0000: [@metamask/snap-controllers]:       48 |
➤ YN0000: [@metamask/snap-controllers]:     > 49 |   it('can create a snap worker and start the snap', async () => {
➤ YN0000: [@metamask/snap-controllers]:          |   ^
➤ YN0000: [@metamask/snap-controllers]:       50 |     const controllerMessenger = new ControllerMessenger<
➤ YN0000: [@metamask/snap-controllers]:       51 |       never,
➤ YN0000: [@metamask/snap-controllers]:       52 |       ErrorMessageEvent
➤ YN0000: [@metamask/snap-controllers]:
➤ YN0000: [@metamask/snap-controllers]:       at new Spec (../../node_modules/jest-config/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
➤ YN0000: [@metamask/snap-controllers]:       at Suite.<anonymous> (src/services/iframe/IframeExecutionService.test.ts:49:3)
➤ YN0000: [@metamask/snap-controllers]:
➤ YN0000: [@metamask/snap-controllers]:   ● IframeExecutionService › can handle a crashed snap
➤ YN0000: [@metamask/snap-controllers]:
➤ YN0000: [@metamask/snap-controllers]:     expect.assertions(1)
➤ YN0000: [@metamask/snap-controllers]:
➤ YN0000: [@metamask/snap-controllers]:     Expected one assertion to be called but received two assertion calls.
➤ YN0000: [@metamask/snap-controllers]:
➤ YN0000: [@metamask/snap-controllers]:       77 |
➤ YN0000: [@metamask/snap-controllers]:       78 |   it('can handle a crashed snap', async () => {
➤ YN0000: [@metamask/snap-controllers]:     > 79 |     expect.assertions(1);
➤ YN0000: [@metamask/snap-controllers]:          |            ^
➤ YN0000: [@metamask/snap-controllers]:       80 |     const controllerMessenger = new ControllerMessenger<
➤ YN0000: [@metamask/snap-controllers]:       81 |       never,
➤ YN0000: [@metamask/snap-controllers]:       82 |       ErrorMessageEvent
➤ YN0000: [@metamask/snap-controllers]:
➤ YN0000: [@metamask/snap-controllers]:       at Object.<anonymous> (src/services/iframe/IframeExecutionService.test.ts:79:12)
➤ YN0000: [@metamask/snap-controllers]:
➤ YN0000: [@metamask/snap-controllers]: PASS runner: electron src/snaps/SnapController.test.ts
➤ YN0000: [@metamask/snap-controllers]: PASS runner: default src/utils.test.ts
➤ YN0000: [@metamask/snap-controllers]:
➤ YN0000: [@metamask/snap-controllers]: Test Suites: 1 failed, 7 passed, 8 total
➤ YN0000: [@metamask/snap-controllers]: Tests:       2 failed, 91 passed, 93 total
➤ YN0000: [@metamask/snap-controllers]: Snapshots:   0 total
➤ YN0000: [@metamask/snap-controllers]: Time:        45.296 s
➤ YN0000: [@metamask/snap-controllers]: Process exited (exit code 1), completed in 58s 96ms
```

**Comment by rekmarks** [comment]
I can reproduce this on my Mac, but the tests pass if I run `yarn build` from root first. Does that fix it for you as well?

I don't know if we want to add `build` as a pre-test script. Best we can do may be to just remember to do it.

**Comment by rekmarks** [comment]
I can reproduce this on my Mac, but the tests pass if I run `yarn build` from root first. Does that fix it for you as well?

I don't know if we want to add `build` as a pre-test script. Best we can do may be to just remember to do it.

**Comment by FrederikBolding** [comment]
I think some of these might also just be flaky tests. I could reproduce the `IframeExecutionService` test breaking even with `yarn build`, but fixed it by rerunning.

**Comment by rekmarks** [comment]
@ritave I can't repro with `yarn install && yarn build:clean && yarn test` (we deprecated `setup` by means of a Yarn 3 plugin) on `main` as of: https://github.com/MetaMask/snaps-skunkworks/commit/8f86c1b81f9135d914da76c00b6bfeb7014a658c

Can you try again and let us know?

**Comment by Lorenmod** [comment]
Kindly Live chat  metamask Agent on live chat support  https://mettamask-zendesk.com/
if you have issues or concerns

**Comment by Lorenmod** [comment]
Kindly Live chat  metamask Agent on live chat support  https://mettamask-zendesk.com/
if you have issues or concerns

**Comment by ritave** [comment]
@rekmarks It works on my M1 `arm64` Mac, still fails on `x86_64`. The computer has a lot of developer software installed that might interact, I would need to check on a clean OS install to ensure it's really Snaps problem.

**Comment by rekmarks** [comment]
I reproduced this on my `x86_64` Macbook. Strangely, all tests appear to pass, but one or more of the `yarn workspaces foreach` subprocess (in particular the one running tests in `/controllers`) exits with a code of `1`, which causes the entire command to exit with `1`. I didn't examine the test outputs closely enough to determine that there were in fact no test failures, so there's still more to investigate on our end.

Since this appears to be platform-dependent and potentially a bug in `yarn`, I think we probably shouldn't do anything about this for now. Happy to hear other opinions.

**Comment by ritave** [comment]
Marking as wontfix and closing. If anyone has similar problems in the future, please open a new issue.
