### ISSUE TITLE
TypeError: AbortController is not a constructor

### ISSUE THREAD

**Issue by andyv09** [MetaMask/snaps-skunkworks#662]
Hey,

I'm trying to implement CeramicNetwork SDK into a snap and I get the following error when trying to run code from a library that uses AbortController API: 
```
TypeError: AbortController is not a constructor
  at new TimedAbortSignal (eval at <anonymous> (eval at <anonymous> (lockdown.umd.min.js:1:18455)), <anonymous>:102095:24)
  at fetchJson (eval at <anonymous> (eval at <anonymous> (lockdown.umd.min.js:1:18455)), <anonymous>:102044:28)
  at Document.createFromGenesis (eval at <anonymous> (eval at <anonymous> (lockdown.umd.min.js:1:18455)), <anonymous>:113225:80)
  at CeramicClient.createStreamFromGenesis (eval at <anonymous> (eval at <anonymous> (lockdown.umd.min.js:1:18455)), <anonymous>:101789:77)
  at TileDocument.createFromGenesis (eval at <anonymous> (eval at <anonymous> (lockdown.umd.min.js:1:18455)), <anonymous>:113004:20)
  at TileLoader.deterministic (eval at <anonymous> (eval at <anonymous> (lockdown.umd.min.js:1:18455)), <anonymous>:114357:98)
  at async DIDDataStore._createIDXDoc (eval at <anonymous> (eval at <anonymous> (lockdown.umd.min.js:1:18455)), <anonymous>:113989:12)
  at async DIDDataStore._getOwnIDXDoc (eval at <anonymous> (eval at <anonymous> (lockdown.umd.min.js:1:18455)), <anonymous>:114009:17)
  at async TileProxy.eval (eval at <anonymous> (eval at <anonymous> (lockdown.umd.min.js:1:18455)), <anonymous>:114028:80)
  at async TileProxy.get (eval at <anonymous> (eval at <anonymous> (lockdown.umd.min.js:1:18455)), <anonymous>:114916:63)
```

AbortController is missing from the window object:
```
window: {
  BigInt: ƒ BigInt()
  Buffer: ƒ c(e,t,r)
  Date: ƒ (...rest)
  Math: Math {abs: ƒ, acos: ƒ, acosh: ƒ, asin: ƒ, asinh: ƒ, …}
  SubtleCrypto: ƒ SubtleCrypto()
  TextDecoder: ƒ TextDecoder()
  TextEncoder: ƒ TextEncoder()
  URL: ƒ URL()
  WebAssembly: WebAssembly {compile: ƒ, validate: ƒ, instantiate: ƒ, compileStreaming: ƒ, instantiateStreaming: ƒ, …}
  WebSocket: ƒ WebSocket()
  atob: ƒ ()
  btoa: ƒ ()
  clearInterval: t=> {…}
  clearTimeout: t=> {…}
  console: console {debug: ƒ, error: ƒ, info: ƒ, log: ƒ, warn: ƒ, …}
  crypto: Crypto {subtle: SubtleCrypto}
  fetch: ƒ ()
  setInterval: (t,r)=> {…}
  setTimeout: (t,r)=> {…}
  wallet: l {_events: {…}, _eventsCount: 1, _maxListeners: 100, _log: console, _state: {…}, …}
}
```

Would it be possible to add AbortController to the list of globals accessible inside sandboxed Snap environment?

Thanks!

**Comment by TaylorBeeston** [comment]
Hey! I actually had the same exact issue (see [this discussion I started about it](https://github.com/MetaMask/snaps-skunkworks/discussions/678)).

In my particular case, I was able to get past this by removing the `TimedAbortSignal` that the ceramic library passes in to fetch.

I am using ESBuild to build my snap, so you're resulting bundle may look different than mine, but I did this by running a sed script over my built js:

```bash
sed -i 's/{ signal: abortSignal }/{}/g' dist/snap.js # or whatever the path to your bundled file is!
```

**Comment by ritave** [comment]
@andyv09 @TaylorBeeston 

We [expose AbortController](https://github.com/MetaMask/snaps-skunkworks/blob/8ba748818220b39fb67198d8b2139c8d0908f1b6/packages/utils/src/default-endowments.ts#L22) in the latest version already. Can you confirm this error still occurs in the latest version of Flask?

If yes, can you please provide a minimal repro?
